language: node_js
node_js: stable
branches:
  only:
  - source
cache:
  apt: true
  directories:
    - node_modules
before_install:
- git config --global user.name "zqf"
- git config --global user.email "736208823@qq.com"
- npm install -g hexo-cli
install:
- npm install
script:
- hexo clean
- hexo generate
after_success:
- cd ./public
- git init
- git add --all .
- git commit -m "Travis CI Auto Builder"
- git push --quiet --force https://3994c3d0e4767e48686f66c1027f8377d9251157@github.com/Godi13/Godi13.github.io.git
  master